// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWfSNyaoJgmzQwycCDML1a_pg8Rvp0JDY',
    appId: '1:1031824783350:web:6264fdba891543f76439d7',
    messagingSenderId: '1031824783350',
    projectId: 'eatelo-auth',
    authDomain: 'eatelo-auth.firebaseapp.com',
    storageBucket: 'eatelo-auth.firebasestorage.app',
    measurementId: 'G-EDVRFWRBLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKQkBkR1N_P0pLq5-YGKOSfeOM5GGykf8',
    appId: '1:1031824783350:android:f2614b952f8e470e6439d7',
    messagingSenderId: '1031824783350',
    projectId: 'eatelo-auth',
    storageBucket: 'eatelo-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuTIsBXsB-whLpO1iowyTcD6CnVs9bJRU',
    appId: '1:1031824783350:ios:0fcfe7bd6a2e46fb6439d7',
    messagingSenderId: '1031824783350',
    projectId: 'eatelo-auth',
    storageBucket: 'eatelo-auth.firebasestorage.app',
    iosBundleId: 'com.example.eatelo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuTIsBXsB-whLpO1iowyTcD6CnVs9bJRU',
    appId: '1:1031824783350:ios:0fcfe7bd6a2e46fb6439d7',
    messagingSenderId: '1031824783350',
    projectId: 'eatelo-auth',
    storageBucket: 'eatelo-auth.firebasestorage.app',
    iosBundleId: 'com.example.eatelo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWfSNyaoJgmzQwycCDML1a_pg8Rvp0JDY',
    appId: '1:1031824783350:web:d2d8ecb21d7c95cd6439d7',
    messagingSenderId: '1031824783350',
    projectId: 'eatelo-auth',
    authDomain: 'eatelo-auth.firebaseapp.com',
    storageBucket: 'eatelo-auth.firebasestorage.app',
    measurementId: 'G-5SM2Y316Q8',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCWfSNyaoJgmzQwycCDML1a_pg8Rvp0JDY',
    appId: '1:1031824783350:web:d2d8ecb21d7c95cd6439d7',
    messagingSenderId: '1031824783350',
    projectId: 'eatelo-auth',
    authDomain: 'eatelo-auth.firebaseapp.com',
    storageBucket: 'eatelo-auth.firebasestorage.app',
    measurementId: 'G-5SM2Y316Q8',
  );

}